# Generated by Django 5.2.1 on 2025-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
